name: Workflow B

on:
  workflow_run:
    workflows: ["main.yml"]
    types:
      - completed
      - failure
      - error


jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: Проверка исходного кода
     uses: actions/checkout@v2
     
   - name: Установка Python
     uses: actions/setup-python@v4
     with:
       python-version: '3.11' # Вы можете указать нужную версию Python
       
   - name: Установка зависимостей
     run: |
       pip install -r requirements.txt
   - name: Запуск тестов
     run: |
       python ORasa.py
